/**
 * scripts/build-icon-sprite.ts
 *
 * Generates apps/web/public/icons/sprite.svg from the SVG source files in
 * apps/web/src/icons/src/.
 *
 * For each *.svg file the script:
 *   1. Strips `width` and `height` attributes from the root <svg> element.
 *   2. Strips explicit `fill="#000000"` / `fill="#000"` path attributes so
 *      icons inherit the surrounding text colour via CSS currentColor.
 *   3. Extracts the `viewBox` value.
 *   4. Extracts the inner SVG content (paths, circles, etc.).
 *   5. Wraps the content as `<symbol id="{stem}" viewBox="...">`.
 *
 * The resulting sprite is a single hidden SVG containing all symbols.
 * `<ServiceIcon iconId="kv" />` references symbol `#kv` via:
 *   <use href="/icons/sprite.svg#kv" />
 *
 * Usage (one-time / on-demand when icons change, per D12 in DECISION_LOG.md):
 *   npx tsx scripts/build-icon-sprite.ts
 *
 * Output: apps/web/public/icons/sprite.svg  (committed to git)
 *
 * Note: The script runs outside of Vite/Worker build pipelines.
 * It requires Node.js 22+ and the `tsx` package (already a devDependency).
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, extname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = resolve(__dirname, "..");

const SRC_DIR = resolve(ROOT, "apps/web/src/icons/src");
const OUT_DIR = resolve(ROOT, "apps/web/public/icons");
const OUT_FILE = resolve(OUT_DIR, "sprite.svg");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function stripAttr(svg: string, attr: string): string {
  return svg.replace(new RegExp(`\\s+${attr}="[^"]*"`, "gi"), "");
}

function extractViewBox(svg: string): string {
  const m = svg.match(/viewBox="([^"]*)"/i);
  return m?.[1] ?? "0 0 24 24";
}

function extractInner(svg: string): string {
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>\s*$/i);
  return m?.[1]?.trim() ?? "";
}

function buildSymbol(iconId: string, svgSource: string): string {
  let src = svgSource;

  // Strip explicit dimensions — viewBox drives sizing in the <use> context
  src = stripAttr(src, "width");
  src = stripAttr(src, "height");

  // Strip black fill overrides so icons inherit currentColor from CSS
  src = src.replace(/\s+fill="#000000"/gi, "");
  src = src.replace(/\s+fill="#000"/gi, "");

  const viewBox = extractViewBox(src);
  const inner = extractInner(src);

  if (!inner) {
    console.warn(`  [warn] no inner content found for ${iconId}.svg — skipping`);
    return "";
  }

  return `  <symbol id="${iconId}" viewBox="${viewBox}">\n    ${inner.replace(/\n/g, "\n    ")}\n  </symbol>`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

console.log("build-icon-sprite: reading source SVGs…");

mkdirSync(OUT_DIR, { recursive: true });

const files = readdirSync(SRC_DIR)
  .filter((f) => extname(f).toLowerCase() === ".svg")
  .sort();

const symbols: string[] = [];
let skipped = 0;

for (const file of files) {
  const iconId = basename(file, ".svg");
  const svgSource = readFileSync(resolve(SRC_DIR, file), "utf-8");
  const symbol = buildSymbol(iconId, svgSource);
  if (symbol) {
    symbols.push(symbol);
  } else {
    skipped++;
  }
}

const sprite = [
  `<!-- Auto-generated by scripts/build-icon-sprite.ts — do not edit manually. -->`,
  `<!-- Re-generate with: npx tsx scripts/build-icon-sprite.ts -->`,
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">`,
  ...symbols,
  `</svg>`,
].join("\n");

writeFileSync(OUT_FILE, sprite, "utf-8");

const sizeKb = (Buffer.byteLength(sprite, "utf-8") / 1024).toFixed(1);
console.log(
  `build-icon-sprite: wrote ${symbols.length} symbols to ${OUT_FILE} (${sizeKb} KB)${
    skipped ? `, skipped ${skipped}` : ""
  }`,
);
