/// <reference path="../.astro/types.d.ts" />

// Note: @astrojs/cloudflare v13 removed Astro.locals.runtime.
// Bindings (DB, CACHE, vars) are accessed via:
//   import { env } from 'cloudflare:workers'
// TypeScript types for those bindings are generated by `wrangler types` into
// worker-configuration.d.ts (Cloudflare.Env / global Env).
// The cfContext ExecutionContext is added to App.Locals automatically by
// @astrojs/cloudflare via .astro/integrations/_astrojs_cloudflare/cloudflare.d.ts.
// Ref: https://docs.astro.build/en/guides/integrations-guide/cloudflare/#removed-astrolocalsruntime-api

declare namespace App {
  interface Locals {
    /**
     * The authenticated user for the current request.
     * Set by `src/middleware.ts` on every request that reaches an authenticated route.
     * `null` for public routes (`/`, `/share/*`).
     */
    user: {
      id: string
      github_id: string
      github_username: string
      email: string
      display_name: string
      avatar_url: string | null
      role: 'admin' | 'user'
    } | null
  }
}
